package dev.sorn.fmp4j.models;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serial;
import java.time.LocalDate;
import java.time.LocalDateTime;

public record FmpBalanceSheetStatement(
        LocalDate date,
        String symbol,
        String reportedCurrency,
        String cik,
        LocalDate filingDate,
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime acceptedDate,
        String fiscalYear,
        String period,
        Long cashAndCashEquivalents,
        Long shortTermInvestments,
        Long cashAndShortTermInvestments,
        Long netReceivables,
        Long accountsReceivables,
        Long otherReceivables,
        Long inventory,
        Long prepaids,
        Long otherCurrentAssets,
        Long totalCurrentAssets,
        Long propertyPlantEquipmentNet,
        Long goodwill,
        Long intangibleAssets,
        Long goodwillAndIntangibleAssets,
        Long longTermInvestments,
        Long taxAssets,
        Long otherNonCurrentAssets,
        Long totalNonCurrentAssets,
        Long otherAssets,
        Long totalAssets,
        Long totalPayables,
        Long accountPayables,
        Long otherPayables,
        Long accruedExpenses,
        Long shortTermDebt,
        Long capitalLeaseObligationsCurrent,
        Long taxPayables,
        Long deferredRevenue,
        Long otherCurrentLiabilities,
        Long totalCurrentLiabilities,
        Long longTermDebt,
        Long capitalLeaseObligationsNonCurrent,
        Long deferredRevenueNonCurrent,
        Long deferredTaxLiabilitiesNonCurrent,
        Long otherNonCurrentLiabilities,
        Long totalNonCurrentLiabilities,
        Long otherLiabilities,
        Long capitalLeaseObligations,
        Long totalLiabilities,
        Long treasuryStock,
        Long preferredStock,
        Long commonStock,
        Long retainedEarnings,
        Long additionalPaidInCapital,
        Long accumulatedOtherComprehensiveIncomeLoss,
        Long otherTotalStockholdersEquity,
        Long totalStockholdersEquity,
        Long totalEquity,
        Long minorityInterest,
        Long totalLiabilitiesAndTotalEquity,
        Long totalInvestments,
        Long totalDebt,
        Long netDebt)
        implements FmpModel {
    @Serial
    private static final long serialVersionUID = 1L;
}
