package dev.sorn.fmp4j.models;

import java.io.Serial;

public record FmpRatioTtm(
        String symbol,
        Double grossProfitMarginTTM,
        Double ebitMarginTTM,
        Double ebitdaMarginTTM,
        Double operatingProfitMarginTTM,
        Double pretaxProfitMarginTTM,
        Double continuousOperationsProfitMarginTTM,
        Double netProfitMarginTTM,
        Double bottomLineProfitMarginTTM,
        Double receivablesTurnoverTTM,
        Double payablesTurnoverTTM,
        Double inventoryTurnoverTTM,
        Double fixedAssetTurnoverTTM,
        Double assetTurnoverTTM,
        Double currentRatioTTM,
        Double quickRatioTTM,
        Double solvencyRatioTTM,
        Double cashRatioTTM,
        Double priceToEarningsRatioTTM,
        Double priceToEarningsGrowthRatioTTM,
        Double forwardPriceToEarningsGrowthRatioTTM,
        Double priceToBookRatioTTM,
        Double priceToSalesRatioTTM,
        Double priceToFreeCashFlowRatioTTM,
        Double priceToOperatingCashFlowRatioTTM,
        Double debtToAssetsRatioTTM,
        Double debtToEquityRatioTTM,
        Double debtToCapitalRatioTTM,
        Double longTermDebtToCapitalRatioTTM,
        Double financialLeverageRatioTTM,
        Double workingCapitalTurnoverRatioTTM,
        Double operatingCashFlowRatioTTM,
        Double operatingCashFlowSalesRatioTTM,
        Double freeCashFlowOperatingCashFlowRatioTTM,
        Double debtServiceCoverageRatioTTM,
        Double interestCoverageRatioTTM,
        Double shortTermOperatingCashFlowCoverageRatioTTM,
        Double operatingCashFlowCoverageRatioTTM,
        Double capitalExpenditureCoverageRatioTTM,
        Double dividendPaidAndCapexCoverageRatioTTM,
        Double dividendPayoutRatioTTM,
        Double dividendYieldTTM,
        Double enterpriseValueTTM,
        Double revenuePerShareTTM,
        Double netIncomePerShareTTM,
        Double interestDebtPerShareTTM,
        Double cashPerShareTTM,
        Double bookValuePerShareTTM,
        Double tangibleBookValuePerShareTTM,
        Double shareholdersEquityPerShareTTM,
        Double operatingCashFlowPerShareTTM,
        Double capexPerShareTTM,
        Double freeCashFlowPerShareTTM,
        Double netIncomePerEBTTTM,
        Double ebtPerEbitTTM,
        Double priceToFairValueTTM,
        Double debtToMarketCapTTM,
        Double effectiveTaxRateTTM,
        Double enterpriseValueMultipleTTM,
        Double dividendPerShareTTM)
        implements FmpModel {
    @Serial
    private static final long serialVersionUID = 1L;
}
