package dev.sorn.fmp4j.types;

import static java.util.Arrays.stream;

import com.fasterxml.jackson.annotation.JsonCreator;
import dev.sorn.fmp4j.exceptions.FmpInvalidIndustryException;

public enum FmpIndustry implements FmpValueObject<String> {
    STEEL("Steel"),
    SILVER("Silver"),
    OTHER_PRECIOUS_METALS("Other Precious Metals"),
    GOLD("Gold"),
    COPPER("Copper"),
    ALUMINUM("Aluminum"),
    PAPER_LUMBER_FOREST_PRODUCTS("Paper, Lumber & Forest Products"),
    INDUSTRIAL_MATERIALS("Industrial Materials"),
    CONSTRUCTION_MATERIALS("Construction Materials"),
    CHEMICALS_SPECIALTY("Chemicals - Specialty"),
    CHEMICALS("Chemicals"),
    AGRICULTURAL_INPUTS("Agricultural Inputs"),
    TELECOMMUNICATIONS_SERVICES("Telecommunications Services"),
    INTERNET_CONTENT_INFORMATION("Internet Content & Information"),
    PUBLISHING("Publishing"),
    BROADCASTING("Broadcasting"),
    ADVERTISING_AGENCIES("Advertising Agencies"),
    ENTERTAINMENT("Entertainment"),
    TRAVEL_LODGING("Travel Lodging"),
    TRAVEL_SERVICES("Travel Services"),
    SPECIALTY_RETAIL("Specialty Retail"),
    LUXURY_GOODS("Luxury Goods"),
    HOME_IMPROVEMENT("Home Improvement"),
    RESIDENTIAL_CONSTRUCTION("Residential Construction"),
    DEPARTMENT_STORES("Department Stores"),
    PERSONAL_PRODUCTS_SERVICES("Personal Products & Services"),
    LEISURE("Leisure"),
    GAMBLING_RESORTS_CASINOS("Gambling, Resorts & Casinos"),
    FURNISHINGS_FIXTURES_APPLIANCES("Furnishings, Fixtures & Appliances"),
    RESTAURANTS("Restaurants"),
    AUTO_PARTS("Auto - Parts"),
    AUTO_MANUFACTURERS("Auto - Manufacturers"),
    AUTO_RECREATIONAL_VEHICLES("Auto - Recreational Vehicles"),
    AUTO_DEALERSHIPS("Auto - Dealerships"),
    APPAREL_RETAIL("Apparel - Retail"),
    APPAREL_MANUFACTURERS("Apparel - Manufacturers"),
    APPAREL_FOOTWEAR_ACCESSORIES("Apparel - Footwear & Accessories"),
    PACKAGING_CONTAINERS("Packaging & Containers"),
    TOBACCO("Tobacco"),
    GROCERY_STORES("Grocery Stores"),
    DISCOUNT_STORES("Discount Stores"),
    HOUSEHOLD_PERSONAL_PRODUCTS("Household & Personal Products"),
    PACKAGED_FOODS("Packaged Foods"),
    FOOD_DISTRIBUTION("Food Distribution"),
    FOOD_CONFECTIONERS("Food Confectioners"),
    AGRICULTURAL_FARM_PRODUCTS("Agricultural Farm Products"),
    EDUCATION_TRAINING_SERVICES("Education & Training Services"),
    BEVERAGES_WINERIES_DISTILLERIES("Beverages - Wineries & Distilleries"),
    BEVERAGES_NON_ALCOHOLIC("Beverages - Non-Alcoholic"),
    BEVERAGES_ALCOHOLIC("Beverages - Alcoholic"),
    URANIUM("Uranium"),
    SOLAR("Solar"),
    OIL_GAS_REFINING_MARKETING("Oil & Gas Refining & Marketing"),
    OIL_GAS_MIDSTREAM("Oil & Gas Midstream"),
    OIL_GAS_INTEGRATED("Oil & Gas Integrated"),
    OIL_GAS_EXPLORATION_PRODUCTION("Oil & Gas Exploration & Production"),
    OIL_GAS_EQUIPMENT_SERVICES("Oil & Gas Equipment & Services"),
    OIL_GAS_ENERGY("Oil & Gas Energy"),
    OIL_GAS_DRILLING("Oil & Gas Drilling"),
    COAL("Coal"),
    SHELL_COMPANIES("Shell Companies"),
    INVESTMENT_BANKING_SERVICES("Investment - Banking & Investment Services"),
    INSURANCE_SPECIALTY("Insurance - Specialty"),
    INSURANCE_REINSURANCE("Insurance - Reinsurance"),
    INSURANCE_PROPERTY_CASUALTY("Insurance - Property & Casualty"),
    INSURANCE_LIFE("Insurance - Life"),
    INSURANCE_DIVERSIFIED("Insurance - Diversified"),
    INSURANCE_BROKERS("Insurance - Brokers"),
    FINANCIAL_MORTGAGES("Financial - Mortgages"),
    FINANCIAL_DIVERSIFIED("Financial - Diversified"),
    FINANCIAL_DATA_STOCK_EXCHANGES("Financial - Data & Stock Exchanges"),
    FINANCIAL_CREDIT_SERVICES("Financial - Credit Services"),
    FINANCIAL_CONGLOMERATES("Financial - Conglomerates"),
    FINANCIAL_CAPITAL_MARKETS("Financial - Capital Markets"),
    BANKS_REGIONAL("Banks - Regional"),
    BANKS_DIVERSIFIED("Banks - Diversified"),
    BANKS("Banks"),
    ASSET_MANAGEMENT("Asset Management"),
    ASSET_MANAGEMENT_BONDS("Asset Management - Bonds"),
    ASSET_MANAGEMENT_INCOME("Asset Management - Income"),
    ASSET_MANAGEMENT_LEVERAGED("Asset Management - Leveraged"),
    ASSET_MANAGEMENT_CRYPTOCURRENCY("Asset Management - Cryptocurrency"),
    ASSET_MANAGEMENT_GLOBAL("Asset Management - Global"),
    MEDICAL_SPECIALTIES("Medical - Specialties"),
    MEDICAL_PHARMACEUTICALS("Medical - Pharmaceuticals"),
    MEDICAL_INSTRUMENTS_SUPPLIES("Medical - Instruments & Supplies"),
    MEDICAL_HEALTHCARE_PLANS("Medical - Healthcare Plans"),
    MEDICAL_HEALTHCARE_INFO_SERVICES("Medical - Healthcare Information Services"),
    MEDICAL_EQUIPMENT_SERVICES("Medical - Equipment & Services"),
    MEDICAL_DISTRIBUTION("Medical - Distribution"),
    MEDICAL_DIAGNOSTICS_RESEARCH("Medical - Diagnostics & Research"),
    MEDICAL_DEVICES("Medical - Devices"),
    MEDICAL_CARE_FACILITIES("Medical - Care Facilities"),
    DRUG_MANUFACTURERS_SPECIALTY_GENERIC("Drug Manufacturers - Specialty & Generic"),
    DRUG_MANUFACTURERS_GENERAL("Drug Manufacturers - General"),
    BIOTECHNOLOGY("Biotechnology"),
    WASTE_MANAGEMENT("Waste Management"),
    TRUCKING("Trucking"),
    RAILROADS("Railroads"),
    AEROSPACE_DEFENSE("Aerospace & Defense"),
    MARINE_SHIPPING("Marine Shipping"),
    INTEGRATED_FREIGHT_LOGISTICS("Integrated Freight & Logistics"),
    AIRLINES_AIRPORTS_AIR_SERVICES("Airlines, Airports & Air Services"),
    GENERAL_TRANSPORTATION("General Transportation"),
    MANUFACTURING_TOOLS_ACCESSORIES("Manufacturing - Tools & Accessories"),
    MANUFACTURING_TEXTILES("Manufacturing - Textiles"),
    MANUFACTURING_MISCELLANEOUS("Manufacturing - Miscellaneous"),
    MANUFACTURING_METAL_FABRICATION("Manufacturing - Metal Fabrication"),
    INDUSTRIAL_DISTRIBUTION("Industrial - Distribution"),
    INDUSTRIAL_SPECIALTIES("Industrial - Specialties"),
    INDUSTRIAL_POLLUTION_TREATMENT_CONTROLS("Industrial - Pollution & Treatment Controls"),
    ENVIRONMENTAL_SERVICES("Environmental Services"),
    INDUSTRIAL_MACHINERY("Industrial - Machinery"),
    INDUSTRIAL_INFRASTRUCTURE_OPERATIONS("Industrial - Infrastructure Operations"),
    INDUSTRIAL_CAPITAL_GOODS("Industrial - Capital Goods"),
    CONSULTING_SERVICES("Consulting Services"),
    BUSINESS_EQUIPMENT_SUPPLIES("Business Equipment & Supplies"),
    STAFFING_EMPLOYMENT_SERVICES("Staffing & Employment Services"),
    RENTAL_LEASING_SERVICES("Rental & Leasing Services"),
    ENGINEERING_CONSTRUCTION("Engineering & Construction"),
    SECURITY_PROTECTION_SERVICES("Security & Protection Services"),
    SPECIALTY_BUSINESS_SERVICES("Specialty Business Services"),
    CONSTRUCTION("Construction"),
    CONGLOMERATES("Conglomerates"),
    ELECTRICAL_EQUIPMENT_PARTS("Electrical Equipment & Parts"),
    AGRICULTURAL_MACHINERY("Agricultural - Machinery"),
    AGRICULTURAL_COMMODITIES_MILLING("Agricultural - Commodities/Milling"),
    REIT_SPECIALTY("REIT - Specialty"),
    REIT_RETAIL("REIT - Retail"),
    REIT_RESIDENTIAL("REIT - Residential"),
    REIT_OFFICE("REIT - Office"),
    REIT_MORTGAGE("REIT - Mortgage"),
    REIT_INDUSTRIAL("REIT - Industrial"),
    REIT_HOTEL_MOTEL("REIT - Hotel & Motel"),
    REIT_HEALTHCARE_FACILITIES("REIT - Healthcare Facilities"),
    REIT_DIVERSIFIED("REIT - Diversified"),
    REAL_ESTATE_SERVICES("Real Estate - Services"),
    REAL_ESTATE_DIVERSIFIED("Real Estate - Diversified"),
    REAL_ESTATE_DEVELOPMENT("Real Estate - Development"),
    REAL_ESTATE_GENERAL("Real Estate - General"),
    INFORMATION_TECH_SERVICES("Information Technology Services"),
    HARDWARE_EQUIPMENT_PARTS("Hardware, Equipment & Parts"),
    COMPUTER_HARDWARE("Computer Hardware"),
    ELECTRONIC_GAMING_MULTIMEDIA("Electronic Gaming & Multimedia"),
    SOFTWARE_SERVICES("Software - Services"),
    SOFTWARE_INFRASTRUCTURE("Software - Infrastructure"),
    SOFTWARE_APPLICATION("Software - Application"),
    SEMICONDUCTORS("Semiconductors"),
    MEDIA_ENTERTAINMENT("Media & Entertainment"),
    COMMUNICATION_EQUIPMENT("Communication Equipment"),
    TECHNOLOGY_DISTRIBUTORS("Technology Distributors"),
    CONSUMER_ELECTRONICS("Consumer Electronics"),
    RENEWABLE_UTILITIES("Renewable Utilities"),
    REGULATED_WATER("Regulated Water"),
    REGULATED_GAS("Regulated Gas"),
    REGULATED_ELECTRIC("Regulated Electric"),
    INDEPENDENT_POWER_PRODUCERS("Independent Power Producers"),
    DIVERSIFIED_UTILITIES("Diversified Utilities"),
    GENERAL_UTILITIES("General Utilities");

    private final String value;

    FmpIndustry(String value) {
        this.value = value;
    }

    @JsonCreator
    public static FmpIndustry industry(String value) {
        return stream(FmpIndustry.values())
                .filter(p -> p.value.equals(value))
                .findFirst()
                .orElseThrow(() -> new FmpInvalidIndustryException("[%s] is not a valid industry", value));
    }

    @Override
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return value();
    }
}
